---

- name: Initialize Kubernetes cluster
  command:
    cmd: kubeadm init --config /tmp/kubeadm-config.yaml
  when: not kubeadm_initialized.stat.exists

- name: Wait for API server
  wait_for:
    host: "{{ ansible_host }}"
    port: 6443
    timeout: 60
